# image will be published to ghcr.io/<user>/<name>
name: my-ublue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr
          # copy static configurations
          #
          # copies config/files/usr into your image's /usr
          #
          # configuration you wish to end up in /etc/ on the booted system
          # should be added into /usr/etc/ as that is the proper "distro"
          # config directory on ostree. Read more in the files module's README

  - type: rpm-ostree
    repos: # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
    neovim
    java-17-openjdk
    powertop
    igt-gpu-tools
    gnome-shell-extension-freon
    gnome-shell-extension-appindicator
    gnome-shell-extension-blur-my-shell
    gnome-shell-extension-dash-to-dock
    virt-install
    libvirt-python
    virt-manager
    virt-install
    libvirt-client
    libguestfs
    qemu-img
    gnome-extensions-app
    f38-backgrounds-extras-gnome
    distrobox
    pipx
    gnome-shell-extension-pop-shell
    yt-dlp
    yt-dlp-bash-completion
    yt-dlp-fish-completion
    fish
    gnome-console

      # - starship
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - justfiles
        # add "!include /usr/share/ublue-os/just/bling.just"
        # in your custom.just (added by default) or local justfile
      - nix-installer # shell shortcuts for determinate system's nix installers
      - ublue-os-wallpapers
      # - ublue-update # https://github.com/ublue-os/ublue-update
      # - dconf-update-service # a service unit that updates the dconf db on boot
      # - devpod # https://devpod.sh/ as an rpm


  - type: yafti
      # if included, yafti and it's dependencies (pip & libadwaita)
      #  will be installed and set up
    custom-flatpaks:
      # this section is optional
      org.chromium.Chromium
      com.github.rafostar.Clapper
      org.mozilla.Thunderbird
      com.bitwarden.desktop
      org.libreoffice.LibreOffice
      org.gnome.TextEditor
      org.gnome.Music
      org.gnome.Podcasts
      org.videolan.VLC
      io.missioncenter.MissionCenter
      app.drey.Dialect
      de.haeckerfelix.Fragments
      de.haeckerfelix.Shortwave
      com.github.hugolabe.Wike
      org.gnome.Solanum
      org.gnome.gitlab.somas.Apostrophe
      

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
